version: '3.5'


services:
  postgres:
    container_name: library_system_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5435:5432"


volumes:
  postgres-db:
    driver: local